apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-cron-job-$(deploymentName)
spec:
  schedule: "$(useTimeMinute) $(currentHour) */1 * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: account-service
          restartPolicy: OnFailure
          containers:
          - name: cleanup-container
            image: bitnami/kubectl
            command: 
            - "sh"
            - "-c"
            - |
              export PATH=$PATH:/shared/usr/bin

              # Run kubectl commands with debugging statements
              INDEX=$(kubectl get ingress ingress-route -o=json | jq -r '.spec.rules[].host' | grep -n "$(deploymentName)api.minhnhut.online" | cut -d: -f1)
              echo "INDEX: $INDEX"
              kubectl patch ingress ingress-route -n default --type json -p "[{'op': 'remove', 'path': '/spec/rules/$((INDEX-1))'}]" 
              
              kubectl delete deployment api-deploy-$(deploymentName) &&
              kubectl delete service api-clusterip-srv-$(deploymentName) &&
              sleep 60 &&
              kubectl delete cronjob cleanup-cron-job-$(deploymentName)
            volumeMounts:
              - name: shared-volume
                mountPath: /shared
          initContainers:
          - name: delete-db-admin-container
            image: mcr.microsoft.com/mssql-tools
            command:
            - /bin/bash
            - -c
            - |
              dbPassword=$(cat /mnt/secrets/SA_PASSWORD)
              serverName=$(cat /mnt/secrets/SQLSERVER)
              /opt/mssql-tools/bin/sqlcmd -S $serverName -U sa -P $dbPassword -Q "
                USE master;
                ALTER DATABASE [AS_ADMIN_1BOSS_$(deploymentName)] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
                DROP DATABASE [AS_ADMIN_1BOSS_$(deploymentName)];"
            volumeMounts:
            - name: secrets-volume
              mountPath: /mnt/secrets
          - name: delete-db-data-container
            image: mcr.microsoft.com/mssql-tools
            command:
            - /bin/bash
            - -c
            - |
              dbPassword=$(cat /mnt/secrets/SA_PASSWORD)
              serverName=$(cat /mnt/secrets/SQLSERVER)
              /opt/mssql-tools/bin/sqlcmd -S $serverName -U sa -P $dbPassword -Q "
                USE master;
                ALTER DATABASE [1BOSS_$(deploymentName)] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
                DROP DATABASE [1BOSS_$(deploymentName)];"
            volumeMounts:
            - name: secrets-volume
              mountPath: /mnt/secrets
          - name: install-tools
            image: debian:stable-slim
            command: ["/bin/sh", "-c"]
            args:
              - apt-get update && apt-get install -y jq
            volumeMounts:
            - name: shared-volume
              mountPath: /shared
          - name: delete-dns-record
            image: mcr.microsoft.com/powershell:latest
            command: 
            - "pwsh"
            - "-command"
            - |
              $apiKey = "$(DNS_APIKEY)"
              $apiSecret = "$(DNS_APISECRET)"
              $domain = "$(DOMAIN)"
              $recordAPIName = "$(deploymentName)api"
              $recordWEBName = "$(deploymentName)web"

              $headers = @{
                  'Authorization' = "sso-key $($apiKey):$($apiSecret)"
                  'Content-Type'  = 'application/json'
              }
              $apiEndpointAPI = "https://api.godaddy.com/v1/domains/$domain/records/A/$recordAPIName"
              $apiEndpointWEB = "https://api.godaddy.com/v1/domains/$domain/records/A/$recordWEBName"

              $responseAPI = Invoke-WebRequest -Uri $apiEndpointAPI -Method Delete -Headers $headers
              $responseWEB = Invoke-WebRequest -Uri $apiEndpointWEB -Method Delete -Headers $headers

              Write-Output $responseAPI
              Write-Output $responseWEB
          volumes:
          - name: secrets-volume
            secret:
              secretName: mssql
          - name: shared-volume
            emptyDir: {}

