apiVersion: batch/v1
kind: Job
metadata:
  name: restore-admin-database-job-$(deploymentName)
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: sqlcmd
        image: mcr.microsoft.com/mssql-tools
        command:
        - /bin/bash
        - -c
        - |
          dbPassword=$(cat /mnt/secrets/SA_PASSWORD)
          /opt/mssql-tools/bin/sqlcmd -S 61.28.229.125 -U sa -P $dbPassword -Q "
            USE [master]
            RESTORE DATABASE [AS_ADMIN_1BOSS_$(deploymentName)]
            FROM DISK = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\AS_ADMIN_1BOSS.bak'
            WITH
                MOVE N'AS_ADMIN_ASOFT' TO N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AS_ADMIN_1BOSS_$(deploymentName).mdf',
                MOVE N'AS_ADMIN_ASOFT_log' TO N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AS_ADMIN_1BOSS_$(deploymentName).ldf',
                NOUNLOAD, REPLACE;"
        volumeMounts:
          - name: secrets-volume
            mountPath: /mnt/secrets
      restartPolicy: OnFailure
      volumes:
        - name: secrets-volume
          secret:
            secretName: mssql
  backoffLimit: 4
